### ISSUE TITLE
Error while building docker image of web-server

### ISSUE THREAD

**Issue by shashankvarshney** [sigopt/sigopt-server#522]
Hi experts,
I am trying to deploy a self hosted sigopt server.

Following are the environment details:

OS : "Ubuntu 22.04.3 LTS"
Kernel: 6.2.0-26-generic
Docker version
==========
Client: Docker Engine - Community
 Version:    25.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.5
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Issue details
========

While building the server, I executed setup.sh script.

Following error was occurred while building web-server docker image:

 _=> ERROR [web-server client-artifacts 2/2] RUN ./scripts/compile/minify_js.sh                                                                                                                          48.9s
------
 > [web-server client-artifacts 2/2] RUN ./scripts/compile/minify_js.sh:
48.77 assets by status 27.4 MiB [cached] 129 assets
48.77 orphan modules 31.2 MiB (javascript) 2.54 KiB (asset) 110 KiB (runtime) [orphan] 2349 modules
48.77 runtime modules 192 KiB 400 modules
48.77 built modules 20.6 MiB (javascript) 6.52 MiB (css/mini-extract) [built]
48.77   modules by path ./node_modules/ 13.4 MiB (javascript) 273 KiB (css/mini-extract)
48.77     javascript modules 13.4 MiB 670 modules
48.77     css modules 273 KiB 4 modules
48.77   modules by path ./web/ 7.18 MiB (javascript) 6.25 MiB (css/mini-extract)
48.77     modules by path ./web/js/ 7.18 MiB (javascript) 349 KiB (css/mini-extract)
48.77       javascript modules 7.18 MiB 83 modules
48.77       css modules 349 KiB 73 modules
48.77     modules by path ./web/styles/less/ 5.91 MiB 34 modules
48.77   util (ignored) 15 bytes [built] [code generated]
48.77   external "btoa" 42 bytes [built] [code generated]
48.77   util (ignored) 15 bytes [built] [code generated]
48.77   external "null" 42 bytes [built] [code generated]
48.77
48.77 ERROR in 86023a414b9ba578b4ee4adf177d399448f0813b/js/pages/vendor-a84f76bf.js
48.77 86023a414b9ba578b4ee4adf177d399448f0813b/js/pages/vendor-a84f76bf.js from Terser plugin
48.77 Cannot read properties of undefined (reading 'TYPE')
48.77 TypeError: Cannot read properties of undefined (reading 'TYPE')
48.77     at shallow_cmp (/sigopt-server/node_modules/terser/dist/bundle.min.js:11252:33)
48.77     at equivalent_to (/sigopt-server/node_modules/terser/dist/bundle.min.js:11257:10)
48.77     at AST_Number.equivalent_to (/sigopt-server/node_modules/terser/dist/bundle.min.js:18771:12)
48.77     at /sigopt-server/node_modules/terser/dist/bundle.min.js:20979:45
48.77     at AST_Binary.optimize (/sigopt-server/node_modules/terser/dist/bundle.min.js:18732:19)
48.77     at Compressor.before (/sigopt-server/node_modules/terser/dist/bundle.min.js:18710:24)
48.77     at AST_Binary.transform (/sigopt-server/node_modules/terser/dist/bundle.min.js:6864:41)
48.77     at /sigopt-server/node_modules/terser/dist/bundle.min.js:7018:29
48.77     at Compressor.before (/sigopt-server/node_modules/terser/dist/bundle.min.js:18705:9)
48.77     at AST_Assign.transform (/sigopt-server/node_modules/terser/dist/bundle.min.js:6864:41)
48.77
48.77 ERROR in 31ed1c0eea2a5259da7ea291b8c20477292447a8/js/pages/vendor-00138493.js
48.77 31ed1c0eea2a5259da7ea291b8c20477292447a8/js/pages/vendor-00138493.js from Terser plugin
48.77 Cannot read properties of undefined (reading 'TYPE')
48.77 TypeError: Cannot read properties of undefined (reading 'TYPE')
48.77     at shallow_cmp (/sigopt-server/node_modules/terser/dist/bundle.min.js:11252:33)
48.77     at equivalent_to (/sigopt-server/node_modules/terser/dist/bundle.min.js:11257:10)
48.77     at AST_Number.equivalent_to (/sigopt-server/node_modules/terser/dist/bundle.min.js:18771:12)
48.77     at /sigopt-server/node_modules/terser/dist/bundle.min.js:20979:45
48.77     at AST_Binary.optimize (/sigopt-server/node_modules/terser/dist/bundle.min.js:18732:19)
48.77     at Compressor.before (/sigopt-server/node_modules/terser/dist/bundle.min.js:18710:24)
48.77     at AST_Binary.transform (/sigopt-server/node_modules/terser/dist/bundle.min.js:6864:41)
48.77     at /sigopt-server/node_modules/terser/dist/bundle.min.js:7018:29
48.77     at Compressor.before (/sigopt-server/node_modules/terser/dist/bundle.min.js:18705:9)
48.77     at AST_Assign.transform (/sigopt-server/node_modules/terser/dist/bundle.min.js:6864:41)
48.77
48.77 ERROR in 86dd76d4cd554fa53787b131d6b1c6fed6aa8111/js/pages/vendor-a84f76bf.js
48.77 86dd76d4cd554fa53787b131d6b1c6fed6aa8111/js/pages/vendor-a84f76bf.js from Terser plugin
48.77 Cannot read properties of undefined (reading 'TYPE')
48.77 TypeError: Cannot read properties of undefined (reading 'TYPE')
48.77     at shallow_cmp (/sigopt-server/node_modules/terser/dist/bundle.min.js:11252:33)
48.77     at equivalent_to (/sigopt-server/node_modules/terser/dist/bundle.min.js:11257:10)
48.77     at AST_Number.equivalent_to (/sigopt-server/node_modules/terser/dist/bundle.min.js:18771:12)
48.77     at /sigopt-server/node_modules/terser/dist/bundle.min.js:20979:45
48.77     at AST_Binary.optimize (/sigopt-server/node_modules/terser/dist/bundle.min.js:18732:19)
48.77     at Compressor.before (/sigopt-server/node_modules/terser/dist/bundle.min.js:18710:24)
48.77     at AST_Binary.transform (/sigopt-server/node_modules/terser/dist/bundle.min.js:6864:41)
48.77     at /sigopt-server/node_modules/terser/dist/bundle.min.js:7018:29
48.77     at Compressor.before (/sigopt-server/node_modules/terser/dist/bundle.min.js:18705:9)
48.77     at AST_Assign.transform (/sigopt-server/node_modules/terser/dist/bundle.min.js:6864:41)
48.77
48.77 ERROR in b315de59e22414e6c3a19f58d55fbbbdfb2e03b4/js/pages/vendor-00138493.js
48.77 b315de59e22414e6c3a19f58d55fbbbdfb2e03b4/js/pages/vendor-00138493.js from Terser plugin
48.77 Cannot read properties of undefined (reading 'TYPE')
48.77 TypeError: Cannot read properties of undefined (reading 'TYPE')
48.77     at shallow_cmp (/sigopt-server/node_modules/terser/dist/bundle.min.js:11252:33)
48.77     at equivalent_to (/sigopt-server/node_modules/terser/dist/bundle.min.js:11257:10)
48.77     at AST_Number.equivalent_to (/sigopt-server/node_modules/terser/dist/bundle.min.js:18771:12)
48.77     at /sigopt-server/node_modules/terser/dist/bundle.min.js:20979:45
48.77     at AST_Binary.optimize (/sigopt-server/node_modules/terser/dist/bundle.min.js:18732:19)
48.77     at Compressor.before (/sigopt-server/node_modules/terser/dist/bundle.min.js:18710:24)
48.77     at AST_Binary.transform (/sigopt-server/node_modules/terser/dist/bundle.min.js:6864:41)
48.77     at /sigopt-server/node_modules/terser/dist/bundle.min.js:7018:29
48.77     at Compressor.before (/sigopt-server/node_modules/terser/dist/bundle.min.js:18705:9)
48.77     at AST_Assign.transform (/sigopt-server/node_modules/terser/dist/bundle.min.js:6864:41)
48.77
48.77 webpack 5.90.3 compiled with 4 errors in 47215 ms
------
failed to solve: process "/bin/sh -c ./scripts/compile/minify_js.sh" did not complete successfully: exit code: 1_

Need help in resolving this issue.

Thanks and regards
Shashank Varshney

**Comment by tjs-intel** [comment]
@shashankvarshney thank you for reporting your issue!

I am trying to reproduce the issue now, but I do not have the same OS or Docker version at the moment. However, given that the build is happening inside a Docker container I am not sure how the container environment would be different than the container in my environment or the container in our CI environment.

Can you please try to clear out your git repository and try the setup command again?
```bash
git clean -fdx
./setup.sh
```

**Comment by tjs-intel** [comment]
This was an issue with proxy settings. Please configure your docker client if you require the use of proxies: https://docs.docker.com/network/proxy/#configure-the-docker-client
